/**
 * 
 */
package fdi.ucm.server.importparser.marcxml.structures.control;

import java.util.HashMap;

import fdi.ucm.server.importparser.marcxml.InterfaceMARCXMLparser;
import fdi.ucm.server.modelComplete.collection.grammar.CompleteElementType;
import fdi.ucm.server.modelComplete.collection.grammar.CompleteIterator;
import fdi.ucm.server.modelComplete.collection.grammar.CompleteTextElementType;

/**
 * @author Joaquin Gayoso-Cabada
 *
 */
public class S6XX implements InterfaceMARCXMLparser {
	
	private CompleteElementType Datos;
	private HashMap<String, HashMap<String, CompleteTextElementType>> TablaD;
	private HashMap<String, HashMap<String, String>> TablaID1;
	private HashMap<String, CompleteTextElementType> TablaD1;
	private HashMap<String, HashMap<String, String>> TablaID2;
	private HashMap<String, CompleteTextElementType> TablaD2;
	private CompleteTextElementType Raro69X;


	public S6XX(CompleteElementType datos,
			HashMap<String, HashMap<String, CompleteTextElementType>> tablaD,
			HashMap<String, HashMap<String, String>> tablaID1,
			HashMap<String, HashMap<String, String>> tablaID2,
			HashMap<String, CompleteTextElementType> tablaD1,
			HashMap<String, CompleteTextElementType> tablaD2) {
		Datos=datos;
		TablaD=tablaD;
		TablaID1=tablaID1;
		TablaD1=tablaD1;
		TablaID2=tablaID2;
		TablaD2=tablaD2;
	}

	/* (non-Javadoc)
	 * @see fdi.ucm.server.importparser.marcxml.InterfaceMARCXMLparser#ProcessAttributes()
	 */
	@Override
	public void ProcessAttributes() {
		
		{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="600";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Personal Name", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Type of personal name entry element", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("0", "Forename");
			full1I.put("1", "Surname");
			full1I.put("3", "Family name");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Version'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Personal name", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Numeration", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Titles and other words associated with a name", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("Dates associated with a name", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType f = new CompleteTextElementType("Date of a work", CTET1);
			CTET1.getSons().add(f);
			full.put("f", f);
			CompleteTextElementType g = new CompleteTextElementType("Miscellaneous information", CTET1);
			CTET1.getSons().add(g);
			full.put("g", g);
			CompleteTextElementType h = new CompleteTextElementType("Medium", CTET1);
			CTET1.getSons().add(h);
			full.put("h", h);
			CompleteTextElementType j = new CompleteTextElementType("Attribution qualifier", CTET1);
			CTET1.getSons().add(j);
			full.put("j", j);
			CompleteTextElementType k = new CompleteTextElementType("Form subheading", CTET1);
			CTET1.getSons().add(k);
			full.put("k", k);
			CompleteTextElementType l = new CompleteTextElementType("Language of a work", CTET1);
			CTET1.getSons().add(l);
			full.put("l", l);
			CompleteTextElementType m = new CompleteTextElementType("Medium of performance for music", CTET1);
			CTET1.getSons().add(m);
			full.put("m", m);
			CompleteTextElementType n = new CompleteTextElementType("Number of part/section of a work", CTET1);
			CTET1.getSons().add(n);
			full.put("n", n);
			CompleteTextElementType o = new CompleteTextElementType("Arranged statement for music", CTET1);
			CTET1.getSons().add(o);
			full.put("o", o);
			CompleteTextElementType p = new CompleteTextElementType("Name of part/section of a work", CTET1);
			CTET1.getSons().add(p);
			full.put("p", p);
			CompleteTextElementType q = new CompleteTextElementType("Fuller form of name", CTET1);
			CTET1.getSons().add(q);
			full.put("q", q);
			CompleteTextElementType r = new CompleteTextElementType("Key for music", CTET1);
			CTET1.getSons().add(r);
			full.put("r", r);
			CompleteTextElementType s = new CompleteTextElementType("Version", CTET1);
			CTET1.getSons().add(s);
			full.put("s", s);
			CompleteTextElementType t = new CompleteTextElementType("Title of a work", CTET1);
			CTET1.getSons().add(t);
			full.put("t", t);
			CompleteTextElementType u = new CompleteTextElementType("Affiliation", CTET1);
			CTET1.getSons().add(u);
			full.put("u", u);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="610";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Corporate Name", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Type of corporate name entry element", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("0", "Inverted name");
			full1I.put("1", "Jurisdiction name");
			full1I.put("2", "Name in direct order");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Corporate name or jurisdiction name as entry element", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Subordinate unit", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Location of meeting", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("Date of meeting or treaty signing", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType f = new CompleteTextElementType("Date of a work", CTET1);
			CTET1.getSons().add(f);
			full.put("f", f);
			CompleteTextElementType g = new CompleteTextElementType("Miscellaneous information", CTET1);
			CTET1.getSons().add(g);
			full.put("g", g);
			CompleteTextElementType h = new CompleteTextElementType("Medium", CTET1);
			CTET1.getSons().add(h);
			full.put("h", h);
			CompleteTextElementType k = new CompleteTextElementType("Form subheading", CTET1);
			CTET1.getSons().add(k);
			full.put("k", k);
			CompleteTextElementType l = new CompleteTextElementType("Language of a work", CTET1);
			CTET1.getSons().add(l);
			full.put("l", l);
			CompleteTextElementType m = new CompleteTextElementType("Medium of performance for music", CTET1);
			CTET1.getSons().add(m);
			full.put("m", m);
			CompleteTextElementType n = new CompleteTextElementType("Number of part/section/meeting", CTET1);
			CTET1.getSons().add(n);
			full.put("n", n);
			CompleteTextElementType o = new CompleteTextElementType("Arranged statement for music", CTET1);
			CTET1.getSons().add(o);
			full.put("o", o);
			CompleteTextElementType p = new CompleteTextElementType("Name of part/section of a work", CTET1);
			CTET1.getSons().add(p);
			full.put("p", p);
			CompleteTextElementType r = new CompleteTextElementType("Key for music", CTET1);
			CTET1.getSons().add(r);
			full.put("r", r);
			CompleteTextElementType s = new CompleteTextElementType("Version", CTET1);
			CTET1.getSons().add(s);
			full.put("s", s);
			CompleteTextElementType t = new CompleteTextElementType("Title of a work", CTET1);
			CTET1.getSons().add(t);
			full.put("t", t);
			CompleteTextElementType u = new CompleteTextElementType("Affiliation", CTET1);
			CTET1.getSons().add(u);
			full.put("u", u);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number or standard number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="611";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Meeting Name", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Type of meeting name entry element", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("0", "Inverted name");
			full1I.put("1", "Jurisdiction name");
			full1I.put("2", "Name in direct order");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Meeting name or jurisdiction name as entry element", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType c = new CompleteTextElementType("Location of meeting", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("Date of meeting", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Subordinate unit", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType f = new CompleteTextElementType("Date of a work", CTET1);
			CTET1.getSons().add(f);
			full.put("f", f);
			CompleteTextElementType g = new CompleteTextElementType("Miscellaneous information", CTET1);
			CTET1.getSons().add(g);
			full.put("g", g);
			CompleteTextElementType h = new CompleteTextElementType("Medium", CTET1);
			CTET1.getSons().add(h);
			full.put("h", h);
			CompleteTextElementType j = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(j);
			full.put("j", j);
			CompleteTextElementType k = new CompleteTextElementType("Form subheading", CTET1);
			CTET1.getSons().add(k);
			full.put("k", k);
			CompleteTextElementType l = new CompleteTextElementType("Language of a work", CTET1);
			CTET1.getSons().add(l);
			full.put("l", l);
			CompleteTextElementType n = new CompleteTextElementType("Number of part/section/meeting", CTET1);
			CTET1.getSons().add(n);
			full.put("n", n);
			CompleteTextElementType p = new CompleteTextElementType("Name of part/section of a work", CTET1);
			CTET1.getSons().add(p);
			full.put("p", p);
			CompleteTextElementType q = new CompleteTextElementType("Name of meeting following jurisdiction name entry element", CTET1);
			CTET1.getSons().add(q);
			full.put("q", q);
			CompleteTextElementType s = new CompleteTextElementType("Version", CTET1);
			CTET1.getSons().add(s);
			full.put("s", s);
			CompleteTextElementType t = new CompleteTextElementType("Title of a work", CTET1);
			CTET1.getSons().add(t);
			full.put("t", t);
			CompleteTextElementType u = new CompleteTextElementType("Affiliation", CTET1);
			CTET1.getSons().add(u);
			full.put("u", u);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number or standard number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="630";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Uniform Title", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Nonfiling characters", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("0", "0 nonfiling characters");
			full1I.put("1", "1 nonfiling characters");
			full1I.put("2", "2 nonfiling characters");
			full1I.put("3", "3 nonfiling characters");
			full1I.put("4", "4 nonfiling characters");
			full1I.put("5", "5 nonfiling characters");
			full1I.put("6", "6 nonfiling characters");
			full1I.put("7", "7 nonfiling characters");
			full1I.put("8", "8 nonfiling characters");
			full1I.put("9", "9 nonfiling characters");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Uniform title", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType d = new CompleteTextElementType("Date of treaty signing", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType f = new CompleteTextElementType("Date of a work", CTET1);
			CTET1.getSons().add(f);
			full.put("f", f);
			CompleteTextElementType g = new CompleteTextElementType("Miscellaneous information", CTET1);
			CTET1.getSons().add(g);
			full.put("g", g);
			CompleteTextElementType h = new CompleteTextElementType("Medium", CTET1);
			CTET1.getSons().add(h);
			full.put("h", h);
			CompleteTextElementType k = new CompleteTextElementType("Form subheading", CTET1);
			CTET1.getSons().add(k);
			full.put("k", k);
			CompleteTextElementType l = new CompleteTextElementType("Language of a work", CTET1);
			CTET1.getSons().add(l);
			full.put("l", l);
			CompleteTextElementType m = new CompleteTextElementType("Medium of performance for music", CTET1);
			CTET1.getSons().add(m);
			full.put("m", m);
			CompleteTextElementType n = new CompleteTextElementType("Number of part/section of a work", CTET1);
			CTET1.getSons().add(n);
			full.put("n", n);
			CompleteTextElementType o = new CompleteTextElementType("Arranged statement for music", CTET1);
			CTET1.getSons().add(o);
			full.put("o", o);
			CompleteTextElementType p = new CompleteTextElementType("Name of part/section of a work", CTET1);
			CTET1.getSons().add(p);
			full.put("p", p);
			CompleteTextElementType r = new CompleteTextElementType("Key for music", CTET1);
			CTET1.getSons().add(r);
			full.put("r", r);
			CompleteTextElementType s = new CompleteTextElementType("Version", CTET1);
			CTET1.getSons().add(s);
			full.put("s", s);
			CompleteTextElementType t = new CompleteTextElementType("Title of a work", CTET1);
			CTET1.getSons().add(t);
			full.put("t", t);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="648";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Chronological Term", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Type of date or time period", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("#", "No information provided");
			full1I.put("0", "Date or time period covered or depicted");
			full1I.put("1", "Date or time period of creation or origin");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Main term portion - Chronological term", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType v = new CompleteTextElementType("Subject subdivision portion - Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("Subject subdivision portion - General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Subject subdivision portion - Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Subject subdivision portion - Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number or standard number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="650";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Topical Term", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Level of subject", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("#", "No information provided");
			full1I.put("0", "No level specified");
			full1I.put("1", "Primary");
			full1I.put("2", "Secondary");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Main term portion - Topical term or geographic name entry element", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Main term portion - Topical term following geographic name entry element", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Main term portion - Location of event", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("Main term portion - Active dates", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Main term portion - Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType n4 = new CompleteTextElementType("Main term portion - Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType v = new CompleteTextElementType("Subject subdivision portion - Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("Subject subdivision portion - General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Subject subdivision portion - Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Subject subdivision portion - Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="651";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Geographic Name", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of heading or term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Name portion - Geographic name", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType e = new CompleteTextElementType("Name portion - Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType n4 = new CompleteTextElementType("Name portion - Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType v = new CompleteTextElementType("Subject subdivision portion - Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("Subject subdivision portion - General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Subject subdivision portion - Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Subject subdivision portion - Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="653";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Index Term - Uncontrolled", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Level of index term", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("#", "No information provided");
			full1I.put("0", "No level specified");
			full1I.put("1", "Primary");
			full1I.put("2", "Secondary");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Type of term or name", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("#", "No information provided");
			full2I.put("0", "Topical term");
			full2I.put("1", "Personal name");
			full2I.put("2", "Corporate name");
			full2I.put("3", "Meeting name");
			full2I.put("4", "Chronological term");
			full2I.put("5", "Geographic name");
			full2I.put("6", "Genre/form term");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Uncontrolled term", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="654";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Faceted Topical Terms", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Level of subject", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("#", "No information provided");
			full1I.put("0", "No level specified");
			full1I.put("1", "Primary");
			full1I.put("2", "Secondary");
			TablaID1.put(Iden, full1I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Focus term", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Non-focus term", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Facet/hierarchy designation", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType e = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="655";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Index Term - Genre/Form", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID1 = new CompleteTextElementType("Type of heading", CTET1);
			CTET1.getSons().add(ID1);
			TablaD1.put(Iden, ID1);
			HashMap<String, String> full1I = new HashMap<String, String>();
			full1I.put("#", "Basic");
			full1I.put("0", "Faceted");
			TablaID1.put(Iden, full1I);
			CompleteTextElementType ID2 = new CompleteTextElementType("Thesaurus", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("0", "Library of Congress Subject Headings");
			full2I.put("1", "LC subject headings for children's literature");
			full2I.put("2", "Medical Subject Headings");
			full2I.put("3", "National Agricultural Library subject authority file");
			full2I.put("4", "Source not specified");
			full2I.put("5", "Canadian Subject Headings");
			full2I.put("6", "Répertoire de vedettes-matière");
			full2I.put("7", "Source specified in subfield 'Source of term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Genre/form data or focus term", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Non-focus term", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Facet/hierarchy designation", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n5 = new CompleteTextElementType("Institution to which field applies", CTET1);
			CTET1.getSons().add(n5);
			full.put("5", n5);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="656";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Index Term - Occupation", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID2 = new CompleteTextElementType("Source of term", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("7", "Source specified in subfield 'Source of term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Occupation", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType k = new CompleteTextElementType("Form", CTET1);
			CTET1.getSons().add(k);
			full.put("k", k);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="657";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Index Term - Function", I1);
			I1.getSons().add(CTET1);
			CompleteTextElementType ID2 = new CompleteTextElementType("Source of term", CTET1);
			CTET1.getSons().add(ID2);
			TablaD2.put(Iden, ID2);
			HashMap<String, String> full2I = new HashMap<String, String>();
			full2I.put("7", "Source specified in subfield 'Source of term'");
			TablaID2.put(Iden, full2I);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Function", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType v = new CompleteTextElementType("Form subdivision", CTET1);
			CTET1.getSons().add(v);
			full.put("v", v);
			CompleteTextElementType x = new CompleteTextElementType("General subdivision", CTET1);
			CTET1.getSons().add(x);
			full.put("x", x);
			CompleteTextElementType y = new CompleteTextElementType("Chronological subdivision", CTET1);
			CTET1.getSons().add(y);
			full.put("y", y);
			CompleteTextElementType z = new CompleteTextElementType("Geographic subdivision", CTET1);
			CTET1.getSons().add(z);
			full.put("z", z);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n3 = new CompleteTextElementType("Materials specified", CTET1);
			CTET1.getSons().add(n3);
			full.put("3", n3);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="658";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Index Term - Curriculum Objective", I1);
			I1.getSons().add(CTET1);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Main curriculum objective", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("Subordinate curriculum objective", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Curriculum code", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("Correlation factor", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of term or code", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}
			{
			CompleteIterator I1=new CompleteIterator(Datos);
			String Iden="662";
			Datos.getSons().add(I1);
			CompleteElementType CTET1=new CompleteElementType("Subject Added Entry - Hierarchical Place Name", I1);
			I1.getSons().add(CTET1);
			HashMap<String, CompleteTextElementType> full = new HashMap<String, CompleteTextElementType>();
			CompleteTextElementType a = new CompleteTextElementType("Country or larger entity", CTET1);
			CTET1.getSons().add(a);
			full.put("a", a);
			CompleteTextElementType b = new CompleteTextElementType("First-order political jurisdiction", CTET1);
			CTET1.getSons().add(b);
			full.put("b", b);
			CompleteTextElementType c = new CompleteTextElementType("Intermediate political jurisdiction", CTET1);
			CTET1.getSons().add(c);
			full.put("c", c);
			CompleteTextElementType d = new CompleteTextElementType("City", CTET1);
			CTET1.getSons().add(d);
			full.put("d", d);
			CompleteTextElementType e = new CompleteTextElementType("Relator term", CTET1);
			CTET1.getSons().add(e);
			full.put("e", e);
			CompleteTextElementType f = new CompleteTextElementType("City subsection", CTET1);
			CTET1.getSons().add(f);
			full.put("f", f);
			CompleteTextElementType g = new CompleteTextElementType("Other nonjurisdictional geographic region and feature", CTET1);
			CTET1.getSons().add(g);
			full.put("g", g);
			CompleteTextElementType h = new CompleteTextElementType("Extraterrestrial area", CTET1);
			CTET1.getSons().add(h);
			full.put("h", h);
			CompleteTextElementType n0 = new CompleteTextElementType("Authority record control number", CTET1);
			CTET1.getSons().add(n0);
			full.put("0", n0);
			CompleteTextElementType n2 = new CompleteTextElementType("Source of heading or term", CTET1);
			CTET1.getSons().add(n2);
			full.put("2", n2);
			CompleteTextElementType n4 = new CompleteTextElementType("Relator code", CTET1);
			CTET1.getSons().add(n4);
			full.put("4", n4);
			CompleteTextElementType n6 = new CompleteTextElementType("Linkage", CTET1);
			CTET1.getSons().add(n6);
			full.put("6", n6);
			CompleteTextElementType n8 = new CompleteTextElementType("Field link and sequence number", CTET1);
			CTET1.getSons().add(n8);
			full.put("8", n8);
			TablaD.put(Iden, full);
			}

			{
//				69X - Local Subject Access Fields (R) Full | Concise
				CompleteIterator I1=new CompleteIterator(Datos);
				Datos.getSons().add(I1);
				Raro69X=new CompleteTextElementType("Local Subject Access Fields", I1);
				I1.getSons().add(Raro69X);
				}
	}

	/* (non-Javadoc)
	 * @see fdi.ucm.server.importparser.marcxml.InterfaceMARCXMLparser#ProcessInstances()
	 */
	@Override
	public void ProcessInstances() {
		// se hace en otro metodo

	}

	public boolean isRaro(String tagS) {
		switch (tagS) {
		case "690":
			return true;
		case "691":
			return true;
		case "692":
			return true;
		case "693":
			return true;
		case "694":
			return true;
		case "695":
			return true;
		case "696":
			return true;
		case "697":
			return true;
		case "698":
			return true;
		case "699":
			return true;
		default:
			return false;
		}
	}

	public CompleteTextElementType getRaro69X() {
		return Raro69X;
	}
}
